plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.app'
}

dependencies {
    implementation xplibs.api.script
    include xplibs.content
    include xplibs.context
    include xplibs.cluster
    include xplibs.project
    include xplibs.export
    include xplibs.portal
    include xplibs.task
    include xplibs.websocket
    include libs.lib.thymeleaf
    include libs.lib.cache
    include libs.lib.httpClient
    include libs.lib.asset
}

repositories {
    mavenCentral()
    xp.enonicRepo( 'dev' )
}
