plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.app'
}

dependencies {
    implementation xplibs.api.script
    include xplibs.content
    include xplibs.context
    include xplibs.cluster
    include xplibs.project
    include xplibs.export
    include xplibs.portal
    include xplibs.task
    include xplibs.websocket
    include libs.lib.thymeleaf
    include libs.lib.cache
    include libs.lib.httpClient
    include libs.lib.asset

    testImplementation "com.enonic.xp:testing:${xpVersion}"
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.3'
}

repositories {
    mavenCentral()
    xp.enonicRepo( 'dev' )
}

test {
    useJUnitPlatform()
}

xp {
    scriptEngines = ['Nashorn', 'GraalJS']
}
